apiVersion: non-margo.org
kind: ApplicationDeployment
metadata:
  name: instance-01
spec:
  appPackageRef:
    id: 4f6769e8-4b1f-4b04-83f1-fe2b47e4d0d1
  deviceRef:
    id: device-101
  deploymentProfile:
    type: helm.v3
    components:
      - name: digitron-orchestrator
        properties:
          repository: oci://northstarida.azurecr.io/charts/northstarida-digitron-orchestrator
          revision: 1.0.9
          wait: true
  parameters:
    pollFrequency:
      value: "60"
      targets:
        - pointer: settings.pollFrequency
          components: [digitron-orchestrator]
