apiVersion: non-margo.org
kind: ApplicationDeployment
metadata:
  name: nextcloud-instance
spec:
  appPackageRef:
    id: 97158541-a90b-4d60-a67c-754900fb76d6  #69391e61-22be-4603-890b-bcbcc32be6cb
  deviceRef:
    id: device-101
  deploymentProfile:
    type: compose
    components:
      - name: nextcloud-stack
        properties:  
          packageLocation: https://raw.githubusercontent.com/docker/awesome-compose/refs/heads/master/nextcloud-redis-mariadb/compose.yaml
  parameters:
    nextcloudPort:
      value: 81
      targets:
        - pointer: PORTS.80
          components: ["nextcloud-stack"]