apiVersion: non-margo.org
kind: ApplicationDeployment
metadata:
  name: instance01
spec:
  appPackageRef:
    id: 69391e61-22be-4603-890b-bcbcc32be6cb
  deviceRef:
    id: device-101
  deploymentProfile:
    type: helm.v3
    components:
      - name: nginx
        properties:  
          repository: oci://ghcr.io/nginxinc/charts/nginx-ingress
          revision: "1.2.2"
          wait: true
  parameters:
    workerProcesses:
      value: "auto"
      targets:
      - pointer: config.workerProcesses
        components: ["nginx"]
    clientMaxBodySize:
      value: "1m"
      targets:
      - pointer: config.clientMaxBodySize
        components: ["nginx"]