# This is an input template allowing the WFM user to modify deployment instance specific parameters.  
# This file is not MARGO specified, however these parameters will be used to create the MARGO ApplicationDeployment
apiVersion: non-margo.org
kind: ApplicationDeployment
metadata:
  name: nextcloud-instance
spec:
  appPackageRef:
    id: {{PACKAGE_ID}}
  deviceRef:
    id: {{DEVICE_ID}}
  deploymentProfile:
    type: compose
    components:
      - name: nextcloud-stack
        properties:  
          packageLocation: {{REPOSITORY}}
  parameters:
    nextcloudPort:
      value: 81
      targets:
        - pointer: PORTS.80
          components: ["nextcloud-stack"]
